# Generated by Django 2.0.1 on 2018-01-05 02:25

from django.db import migrations, models
import eufacopartesite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.IntegerField()),
                ('page', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=eufacopartesite.models.upload_localtion, width_field='width_field')),
            ],
        ),
    ]
