# Generated by Django 2.0.1 on 2018-01-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eufacopartesite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpicture',
            name='user',
        ),
    ]
