# Generated by Django 2.0.1 on 2018-01-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eufacopartesite', '0002_remove_eventpicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpicture',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media_cnd/', width_field='width_field'),
        ),
    ]
