# Generated by Django 2.0.1 on 2018-01-09 23:23

from django.db import migrations, models
import eufacopartesite.models


class Migration(migrations.Migration):

    dependencies = [
        ('eufacopartesite', '0003_auto_20180109_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpicture',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=eufacopartesite.models.upload_location, width_field='width_field'),
        ),
    ]
